### ISSUE TITLE
Event Tracking Example?

### ISSUE THREAD

**Issue by someguy9** [connorlindsey/bento-nextjs-sdk#1]
Would love to see an event tracking example in the read me, is it possible with this package?

**Comment by connorlindsey** [comment]
Hey, you can absolutely use the package for event tracking. If you're using the `<BentoAnalytics />` (or legacy) component, you can use the Bento JS SDK via the window like:

```
window.bento.track("optin", {"organisation_name": "Team Rocket"});
window.bento.track("demo");
window.bento.track("download");
```

Or if you'd like to track an event from a server action, api route, etc, you can use the Bento Node SDK: https://github.com/bentonow/bento-node-sdk?tab=readme-ov-file#trackparameters-trackparameterss-e-promiseboolean

I'll update the readme and provided types!

**Comment by someguy9** [comment]
Just curious should the event names have a dollar sign before them

**Comment by connorlindsey** [comment]
I don't think it is required and is just a convention some teams use, but I'll cc @jessehanley to double check

**Comment by someguy9** [comment]
Thank you! I just know all the examples use it so that's what I do

**Comment by jessehanley** [comment]
@connorlindsey is correcto. Some people like to leave them out in their events so they can tell the difference between Bento ones and theirs.
